# Generated by Django 3.2.13 on 2022-07-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
